module.exports = {
	writeCommentInline: '${emoji.pencil2}',
	writeNewCommentInline: '${emoji.speech_balloon}${emoji.pencil2}',
	commentsCountInline: '${emoji.speech_balloon}',
	abbr1k: 'K',
	abbr1m: 'M',
	Post: 'Post',
	from: 'from',
	channel: 'channel',
	linkIcon: '${emoji.globe_with_meridians}',
	linkImage: '${emoji.frame_with_picture}',
	Back: 'Back',
	toTred: 'to tred ${emoji.speech_balloon}',
	AnswerToUser: 'Answer',
	pencilIcon: '${emoji.pencil2}',
	utc: 'utc',
	trashCanIcon: '${emoji.wastebasket}',
	ReplyFromTred: 'Reply from tred',
	OpenTred: 'Open tred',
	commentsIcon: '${emoji.speech_balloon}',
	NewComment: 'New comment',
	Tip: 'Tip',
	AboutTime: 'time is at UTC ${emoji.globe_with_meridians}',
	textDelimiter: '  |  ',
	DeletedByUser: '[deleted by user]',
	DeletedByAdmin: '[deleted by admin]',
	DeletedUsername: '[username]',
	TredLevel: 'Tred level',
	byComment: 'by comment',
	SubscribeSettings: 'Subscribe settings',
	SubscribeSettingsBell: '${emoji.bell}'
}
