module.exports = {
	writeCommentInline: '${emoji.pencil2}',
	writeNewCommentInline: '${emoji.speech_balloon}${emoji.pencil2}',
	commentsCountInline: '${emoji.speech_balloon}',
	abbr1k: 'K',
	abbr1m: 'M',
	Post: 'Post',
	from: 'de',
	channel: 'canal',
	linkIcon: '${emoji.globe_with_meridians}',
	linkImage: '${emoji.frame_with_picture}',
	Back: 'Voltar',
	toTred: 'ao tópico ${emoji.speech_balloon}',
	AnswerToUser: 'Responder',
	pencilIcon: '${emoji.pencil2}',
	utc: 'utc',
	trashCanIcon: '${emoji.wastebasket}',
	ReplyFromTred: 'Resposta à discussão',
	OpenTred: 'Abrir discussão',
	commentsIcon: '${emoji.speech_balloon}',
	NewComment: 'Novo comentário',
	Tip: 'Dica',
	AboutTime: 'o horário é UTC ${emoji.globe_with_meridians}',
	textDelimiter: '  |  ',
	DeletedByUser: '[removido pelo usuário]',
	DeletedByAdmin: '[removido pelo moderador]',
	DeletedUsername: '[nome de usuário]',
	TredLevel: 'Tópico',
	byComment: 'por comentário',
	SubscribeSettings: 'Opções de inscrição',
	SubscribeSettingsBell: '${emoji.bell}'
}
